# Pré-Processamento de Dados

Pré processamento de dados utilizando o guia completo por
[@caiquecoelho](https://medium.com/@caiquecoelho).

Disciplina: Mineração de Dados

Aluna: Sofia Bressa.

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler
from sklearn.decomposition import PCA

bc_df = pd.read_csv("breast_cancer.csv")
cmc_df = pd.read_csv("cmc.csv")
iris_df = pd.read_csv("iris.csv")

In [ ]:
# Breast Cancer
bc_df_clean = bc_df.drop(columns=['id'])
label_encoder = LabelEncoder()
bc_df_clean['diagnosis'] = label_encoder.fit_transform(bc_df_clean['diagnosis'])

# Separar X e Y
X_bc = bc_df_clean.drop(columns=['diagnosis'])
Y_bc = bc_df_clean['diagnosis']

# Padronização
scaler = StandardScaler()
X_bc_scaled = scaler.fit_transform(X_bc)

# PCA
pca = PCA(n_components=2)
X_bc_pca = pca.fit_transform(X_bc_scaled)

# DataFrame final
bc_pca_df = pd.DataFrame(X_bc_pca, columns=['PC1', 'PC2'])
bc_pca_df['Diagnosis'] = Y_bc
bc_pca_df.head()

        PC1        PC2  Diagnosis
0  9.192837   1.948583          1
1  2.387802  -3.768172          1
2  5.733896  -1.075174          1
3  7.122953  10.275589          1
4  3.935302  -1.948072          1

In [ ]:
# CMC
X_cmc = cmc_df.drop(columns=['ContraceptiveMethod'])
Y_cmc = cmc_df['ContraceptiveMethod']
X_cmc_encoded = pd.get_dummies(X_cmc, columns=['HusbandOccupation'])

# Normalização
minmax_scaler = MinMaxScaler()
X_cmc_scaled = minmax_scaler.fit_transform(X_cmc_encoded)

# DataFrame final
X_cmc_scaled_df = pd.DataFrame(X_cmc_scaled, columns=X_cmc_encoded.columns)
X_cmc_scaled_df['ContraceptiveMethod'] = Y_cmc
X_cmc_scaled_df.head()

,WifeAge,WifeEducation,HusbandEducation,NumChildren,WifeReligion,WifeWorking,LivingStandardIndex,MediaExposure,HusbandOccupation_1,HusbandOccupation_2,HusbandOccupation_3,HusbandOccupation_4,ContraceptiveMethod
0,0.242424,0.333333,0.666667,0.1875,1.0,1.0,0.666667,0.0,0.0,1.0,0.0,0.0,1
1,0.878788,0.000000,0.666667,0.6250,1.0,1.0,1.000000,0.0,0.0,0.0,1.0,0.0,1
2,0.818182,0.333333,0.666667,0.4375,1.0,1.0,1.000000,0.0,0.0,0.0,1.0,0.0,1
3,0.787879,0.666667,0.333333,0.5625,1.0,1.0,0.666667,0.0,0.0,0.0,1.0,0.0,1
4,0.606061,0.666667,0.666667,0.5000,1.0,1.0,0.333333,0.0,0.0,0.0,1.0,0.0,1

In [ ]:
# Iris
X_iris = iris_df.drop(columns=['variety'])
Y_iris = iris_df['variety']

# Codificação da variável categórica
label_encoder = LabelEncoder()
Y_iris_encoded = label_encoder.fit_transform(Y_iris)

# Padronização
scaler = StandardScaler()
X_iris_scaled = scaler.fit_transform(X_iris)

# PCA
pca = PCA(n_components=2)
X_iris_pca = pca.fit_transform(X_iris_scaled)

# DataFrame final
iris_pca_df = pd.DataFrame(X_iris_pca, columns=['PC1', 'PC2'])
iris_pca_df['Variety'] = Y_iris
iris_pca_df.head()

        PC1       PC2 Variety
0 -2.264703  0.480027  Setosa
1 -2.080961 -0.674134  Setosa
2 -2.364229 -0.341908  Setosa
3 -2.299384 -0.597395  Setosa
4 -2.389842  0.646835  Setosa